services:

  fastcontext:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fastcontext

    depends_on:
      tests:
        condition: service_completed_successfully

    working_dir: /app

    volumes:
      - .:/app

    environment:
      PYTHONPATH: /app
      FASTCONTEXT_ENV: development

    ports:
      - "8501:8501"

    stdin_open: true
    tty: true

  tests:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /app

    volumes:
      - .:/app

    environment:
      PYTHONPATH: /app
      FASTCONTEXT_ENV: test

    command: ["python", "-m", "pytest", "-v"]
    restart: "no"